### Get All Files
GET https://server-crud-node.onrender.com/users

### Get File by Id

GET https://server-crud-node.onrender.com/users/63e4e4bf5b0ac537cb8d31de

### Create File

POST https://server-crud-node.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "name":"da",
    "email":"da@gmail.com",
    "password":"dada",
    "data":""
}

### Delete File

DELETE https://server-crud-node.onrender.com/users/63e563319d8aefb0e337080f
